#!/usr/bin/env bash
# Wrapper that calls statusline-command.py with env vars.

export CLAUDE_STATUSLINE_HOSTNAME=0
export CLAUDE_STATUSLINE_CHANGES=0
export CLAUDE_STATUSLINE_12H_COST=0
export CLAUDE_STATUSLINE_24H_COST=1
export CLAUDE_STATUSLINE_CACHE_HIT=0
export CLAUDE_STATUSLINE_APPLE_SILICON=0
export CLAUDE_STATUSLINE_BATTERY=0
export CLAUDE_STATUSLINE_RENDER_TIME=0
export CLAUDE_STATUSLINE_SESSIONS=0

exec "$(dirname "${BASH_SOURCE[0]}")/statusline-command.py" "$@"
