auto-update-channel = stable

window-inherit-working-directory = false
tab-inherit-working-directory = false
split-inherit-working-directory = true
working-directory = home

window-save-state = always
confirm-close-surface = false

window-new-tab-position = end

clipboard-paste-protection = false

bell-features = no-attention, no-title

keybind = "cmd+shift+left=previous_tab"
keybind = "cmd+shift+right=next_tab"
keybind = ctrl+shift+left=goto_split:previous
keybind = ctrl+shift+right=goto_split:next

font-family = JetBrains Mono
font-style = Regular
font-size = 13
font-thicken = true

scrollback-limit = 256000000

background-opacity = 0.95

split-divider-color = #7a2222

background = #000000
foreground = #80ff5d

selection-background = #093ae9
selection-foreground = #a9bbff

cursor-color = #38ff27
cursor-text  = #000000

palette = 0  = #000000
palette = 1  = #c25c48
palette = 2  = #00a600
palette = 3  = #999900
palette = 4  = #4e31d8
palette = 5  = #b200b2
palette = 6  = #00a6b2
palette = 7  = #bfbfbf
palette = 8  = #666666
palette = 9  = #e50000
palette = 10 = #80ff5c
palette = 11 = #e5e500
palette = 12 = #651dff
palette = 13 = #e500e5
palette = 14 = #00e5e5
palette = 15 = #e5e5e5
