#!/usr/bin/env bash
# Prevent commands that trigger "Command contains quoted characters in flag names"
# warning in Claude Code. Blocks the command and nudges Claude to reformulate.
# See: https://github.com/anthropics/claude-code/issues/27957
set -euo pipefail

# Feature flags (set to 1 to enable, 0 to disable)
BLOCK_COMPOUND_COMMANDS="${BLOCK_COMPOUND_COMMANDS:-0}"

cmd=$(jq -r '.tool_input.command // ""')

# Strip strings inside single and double quotes to avoid false positives
# on quoted content within heredocs, variable assignments, etc.
stripped=$(echo "$cmd" | sed -e "s/'[^']*'//g" -e 's/"[^"]*"//g')

# Block compound commands (&&, ||, ;) — these combined with quoted strings
# are the most common trigger for the warning
if [[ "$BLOCK_COMPOUND_COMMANDS" == "1" ]] && echo "$stripped" | grep -Eq '(\s&&\s|\s\|\|\s|;\s*\S)'; then
  cat >&2 <<'EOF'
BLOCKED: Do not chain commands with &&, ||, or ;
These trigger the "quoted characters in flag names" confirmation prompt.
Run each command as a separate Bash tool call instead.
EOF
  exit 2
fi

# Block flags with embedded quotes: --flag="value" or --flag='value'
if echo "$cmd" | grep -Eq -- '-[a-zA-Z0-9_-]+=["\x27]'; then
  cat >&2 <<'EOF'
BLOCKED: Do not use quoted values attached to flags (e.g., --flag="value").
This triggers the "quoted characters in flag names" prompt.
Instead use: --flag value (space-separated, no quotes), or a heredoc for complex values.
EOF
  exit 2
fi

# Block echo/printf with quoted strings containing special chars like ---
# These are commonly generated by Claude and trigger the warning
if echo "$cmd" | grep -Eq '(echo|printf)\s+["\x27]'; then
  cat >&2 <<'EOF'
BLOCKED: Avoid echo/printf with quoted strings — they trigger the "quoted characters
in flag names" prompt. If you need to separate output, use a comment or run commands
as separate Bash tool calls.
EOF
  exit 2
fi

exit 0
